[package]
name = "namegen"
version = "0.0.1"
authors = ["mkingsley"]
edition = "2018"
license = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markovr = "^0.4"
roxmltree = "^0.13"
