[package]
name = "namegen"
version = "0.0.1"
authors = ["mkingsley"]
edition = "2018"
license = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markov = "1.1"
roxmltree = "^0.13"
random-pick = "^1.2"
rand = "^0.8"